const episodes = [
"Adventure Time Season 10 Episode 12 – Gumbaldia",
"Adventure Time Season 10 Episode 11 – Temple of Mars",
"Adventure Time Season 10 Episode 10 – Jake the Starchild",
"Adventure Time Season 10 Episode 9 – Blenanas",
"Adventure Time Season 10 Episode 8 – The First Investigation",
"Adventure Time Season 10 Episode 7 – Marcy & Hunson",
"Adventure Time Season 10 Episode 6 – Ring of Fire",
"Adventure Time Season 10 Episode 5 – Seventeen",
"Adventure Time Season 10 Episode 4 – Bonnibel Bubblegum",
"Adventure Time Season 10 Episode 3 – Son of Rap Bear",
"Adventure Time Season 10 Episode 2 – Always BMO Closing",
"Adventure Time Season 10 Episode 1 – The Wild Hunt",
"Adventure Time Season 9 Episode 14 – Three Buckets",
"Adventure Time Season 9 Episode 13 – Whispers",
"Adventure Time Season 9 Episode 12 – Fionna and Cake and Fionna",
"Adventure Time Season 9 Episode 11 – Ketchup",
"Adventure Time Season 9 Episode 10 – Abstract",
"Adventure Time Season 9 Episode 9 – Elements Part 8: Skyhooks II",
"Adventure Time Season 9 Episode 8 – Elements Part 7: Hero Heart",
"Adventure Time Season 9 Episode 7 – Elements Part 6: Happy Warrior",
"Adventure Time Season 9 Episode 6 – Elements Part 5: Slime Central",
"Adventure Time Season 9 Episode 5 – Elements Part 4: Cloudy",
"Adventure Time Season 9 Episode 4 – Elements Part 3: Winter Light",
"Adventure Time Season 9 Episode 3 – Elements Part 2: Bespoken For",
"Adventure Time Season 9 Episode 2 – Elements Part 1: Skyhooks",
"Adventure Time Season 9 Episode 1 – Orb",
"Adventure Time Season 8 Episode 27 – Islands Part 8: The Light Cloud",
"Adventure Time Season 8 Episode 26 – Islands Part 7: Helpers",
"Adventure Time Season 8 Episode 25 – Islands Part 6: Min & Marty",
"Adventure Time Season 8 Episode 24 – Islands Part 5: Hide and Seek",
"Adventure Time Season 8 Episode 23 – Islands Part 4: Imaginary Resources",
"Adventure Time Season 8 Episode 22 – Islands Part 3: Mysterious Island",
"Adventure Time Season 8 Episode 21 – Islands Part 2: Whipple the Happy Dragon",
"Adventure Time Season 8 Episode 20 – Islands Part 1: The Invitation",
"Adventure Time Season 8 Episode 19 – Jelly Beans Have Power",
"Adventure Time Season 8 Episode 18 – Horse and Ball",
"Adventure Time Season 8 Episode 17 – High Strangeness",
"Adventure Time Season 8 Episode 16 – Wheels",
"Adventure Time Season 8 Episode 15 – Do No Harm",
"Adventure Time Season 8 Episode 14 – Two Swords",
"Adventure Time Season 8 Episode 12-13 – Preboot / Reboot",
"Adventure Time Season 8 Episode 11 – Daddy-Daughter Card Wars",
"Adventure Time Season 8 Episode 10 – The Music Hole",
"Adventure Time Season 8 Episode 9 – Five Short Tables",
"Adventure Time Season 8 Episode 8 – Elemental",
"Adventure Time Season 8 Episode 7 – Normal Man",
"Adventure Time Season 8 Episode 6 – Bun Bun",
"Adventure Time Season 8 Episode 5 – I Am a Sword",
"Adventure Time Season 8 Episode 4 – Lady Rainicorn of the Crystal Dimension",
"Adventure Time Season 8 Episode 3 – Beyond the Grotto",
"Adventure Time Season 8 Episode 2 – Don’t Look",
"Adventure Time Season 8 Episode 1 – Broke His Crown",
"Adventure Time Season 7 Episode 26 – The Thin Yellow Line",
"Adventure Time Season 7 Episode 25 – Flute Spell",
"Adventure Time Season 7 Episode 24 – The Hall of Egress",
"Adventure Time Season 7 Episode 23 – Crossover",
"Adventure Time Season 7 Episode 22 – Scamps",
"Adventure Time Season 7 Episode 21 – King’s Ransom",
"Adventure Time Season 7 Episode 20 – Bad Jubies",
"Adventure Time Season 7 Episode 19 – Blank-Eyed Girl",
"Adventure Time Season 7 Episode 18 – President Porpoise Is Missing!",
"Adventure Time Season 7 Episode 17 – Angel Face",
"Adventure Time Season 7 Episode 16 – Summer Showers",
"Adventure Time Season 7 Episode 14-15 – The More You Moe, the Moe You Know",
"Adventure Time Season 7 Episode 13 – The Dark Cloud (Stakes Part 8)",
"Adventure Time Season 7 Episode 12 – Checkmate (Stakes Part 7)",
"Adventure Time Season 7 Episode 11 – Take Her Back (Stakes Part 6)",
"Adventure Time Season 7 Episode 10 – May I Come In? (Stakes Part 5)",
"Adventure Time Season 7 Episode 9 – The Empress Eyes (Stakes Part 4)",
"Adventure Time Season 7 Episode 8 – Vamps About (Stakes Part 3)",
"Adventure Time Season 7 Episode 7 – Everything Stays (Stakes Part 2)",
"Adventure Time Season 7 Episode 6 – Marceline the Vampire Queen (Stakes Part 1)",
"Adventure Time Season 7 Episode 5 – Football",
"Adventure Time Season 7 Episode 4 – Mama Said",
"Adventure Time Season 7 Episode 3 – Cherry Cream Soda",
"Adventure Time Season 7 Episode 2 – Varmints",
"Adventure Time Season 7 Episode 1 – Bonnie & Neddy",
"Adventure Time Season 6 Episode 43 – The Comet",
"Adventure Time Season 6 Episode 42 – Hot Diggity Doom",
"Adventure Time Season 6 Episode 41 – On the Lam",
"Adventure Time Season 6 Episode 40 – Orgalorg",
"Adventure Time Season 6 Episode 39 – Be Sweet",
"Adventure Time Season 6 Episode 38 – You Forgot Your Floaties",
"Adventure Time Season 6 Episode 37 – Water Park Prank",
"Adventure Time Season 6 Episode 36 – Hoots",
"Adventure Time Season 6 Episode 35 – Graybles 1000+",
"Adventure Time Season 6 Episode 34 – Chips & Ice Cream",
"Adventure Time Season 6 Episode 33 – Jermaine",
"Adventure Time Season 6 Episode 32 – Friends Forever",
"Adventure Time Season 6 Episode 31 – Walnuts & Rain",
"Adventure Time Season 6 Episode 30 – The Diary",
"Adventure Time Season 6 Episode 29 – Dark Purple",
"Adventure Time Season 6 Episode 28 – The Mountain",
"Adventure Time Season 6 Episode 27 – The Visitor",
"Adventure Time Season 6 Episode 26 – Gold Stars",
"Adventure Time Season 6 Episode 25 – Astral Plane",
"Adventure Time Season 6 Episode 24 – Evergreen",
"Adventure Time Season 6 Episode 23 – The Pajama War",
"Adventure Time Season 6 Episode 22 – The Cooler",
"Adventure Time Season 6 Episode 21 – Dentist",
"Adventure Time Season 6 Episode 20 – Jake the Brick",
"Adventure Time Season 6 Episode 19 – Is That You?",
"Adventure Time Season 6 Episode 18 – Everything’s Jake",
"Adventure Time Season 6 Episode 17 – Ghost Fly",
"Adventure Time Season 6 Episode 16 – Joshua & Margaret Investigations",
"Adventure Time Season 6 Episode 15 – Nemesis",
"Adventure Time Season 6 Episode 14 – Princess Day",
"Adventure Time Season 6 Episode 13 – Thanks for the Crabapples, Giuseppe!",
"Adventure Time Season 6 Episode 12 – Ocarina",
"Adventure Time Season 6 Episode 11 – Little Brother",
"Adventure Time Season 6 Episode 10 – Something Big",
"Adventure Time Season 6 Episode 9 – The Prince Who Wanted Everything",
"Adventure Time Season 6 Episode 8 – Furniture & Meat",
"Adventure Time Season 6 Episode 7 – Food Chain",
"Adventure Time Season 6 Episode 6 – Breezy",
"Adventure Time Season 6 Episode 5 – Sad Face",
"Adventure Time Season 6 Episode 4 – The Tower",
"Adventure Time Season 6 Episode 3 – James II",
"Adventure Time Season 6 Episode 1-2 – Wake Up / Escape From the Citadel",
"Adventure Time Season 5 Episode 52 – Billy’s Bucket List",
"Adventure Time Season 5 Episode 50-51 – Lemonhope",
"Adventure Time Season 5 Episode 49 – Bad Timing",
"Adventure Time Season 5 Episode 48 – Betty",
"Adventure Time Season 5 Episode 47 – The Red Throne",
"Adventure Time Season 5 Episode 46 – Rattleballs",
"Adventure Time Season 5 Episode 45 – Blade of Grass",
"Adventure Time Season 5 Episode 44 – Apple Wedding",
"Adventure Time Season 5 Episode 43 – Root Beer Guy",
"Adventure Time Season 5 Episode 42 – James",
"Adventure Time Season 5 Episode 41 – Vault of Bones",
"Adventure Time Season 5 Episode 40 – Play Date",
"Adventure Time Season 5 Episode 39 – We Fixed a Truck",
"Adventure Time Season 5 Episode 38 – Red Starved",
"Adventure Time Season 5 Episode 37 – Box Prince",
"Adventure Time Season 5 Episode 36 – Dungeon Train",
"Adventure Time Season 5 Episode 35 – Love Games",
"Adventure Time Season 5 Episode 34 – The Vault",
"Adventure Time Season 5 Episode 33 – Time Sandwich",
"Adventure Time Season 5 Episode 32 – Earth & Water",
"Adventure Time Season 5 Episode 31 – Too Old",
"Adventure Time Season 5 Episode 30 – Lemonhope Part 2",
"Adventure Time Season 5 Episode 29 – Lemonhope Part 1",
"Adventure Time Season 5 Episode 28 – Sky Witch",
"Adventure Time Season 5 Episode 27 – Frost & Fire",
"Adventure Time Season 5 Episode 26 – Wizards Only, Fools",
"Adventure Time Season 5 Episode 25 – Candy Streets",
"Adventure Time Season 5 Episode 24 – Another Five More Short Graybles",
"Adventure Time Season 5 Episode 23 – One Last Job",
"Adventure Time Season 5 Episode 22 – The Suitor",
"Adventure Time Season 5 Episode 21 – The Party’s Over, Isla de Señorita",
"Adventure Time Season 5 Episode 20 – Shh!",
"Adventure Time Season 5 Episode 19 – James Baxter the Horse",
"Adventure Time Season 5 Episode 18 – Princess Potluck",
"Adventure Time Season 5 Episode 17 – BMO Lost",
"Adventure Time Season 5 Episode 16 – Puhoy",
"Adventure Time Season 5 Episode 15 – A Glitch Is a Glitch",
"Adventure Time Season 5 Episode 14 – Simon & Marcy",
"Adventure Time Season 5 Episode 13 – The Great Bird Man",
"Adventure Time Season 5 Episode 12 – Vault of Bones",
"Adventure Time Season 5 Episode 11 – Bad Little Boy",
"Adventure Time Season 5 Episode 10 – Little Dude",
"Adventure Time Season 5 Episode 9 – All Your Fault",
"Adventure Time Season 5 Episode 8 – Mystery Dungeon",
"Adventure Time Season 5 Episode 7 – Davey",
"Adventure Time Season 5 Episode 6 – Jake the Dad",
"Adventure Time Season 5 Episode 5 – All the Little People",
"Adventure Time Season 5 Episode 4 – Up a Tree",
"Adventure Time Season 5 Episode 3 – Five More Short Graybles",
"Adventure Time Season 5 Episode 2 – Jake the Dog",
"Adventure Time Season 5 Episode 1 – Finn the Human",
"Adventure Time Season 4 Episode 26 – The Lich",
"Adventure Time Season 4 Episode 25 – I Remember You",
"Adventure Time Season 4 Episode 24 – Sons of Mars",
"Adventure Time Season 4 Episode 23 – The Hard Easy",
"Adventure Time Season 4 Episode 22 – Ignition Point",
"Adventure Time Season 4 Episode 21 – Who Would Win",
"Adventure Time Season 4 Episode 20 – You Made Me",
"Adventure Time Season 4 Episode 19 – Lady & Peebles",
"Adventure Time Season 4 Episode 18 – King Worm",
"Adventure Time Season 4 Episode 17 – BMO Noire",
"Adventure Time Season 4 Episode 16 – Burning Low",
"Adventure Time Season 4 Episode 15 – Sons of Mars",
"Adventure Time Season 4 Episode 14 – Card Wars",
"Adventure Time Season 4 Episode 13 – Princess Cookie",
"Adventure Time Season 4 Episode 12 – Gotcha!",
"Adventure Time Season 4 Episode 11 – Beyond This Earthly Realm",
"Adventure Time Season 4 Episode 10 – Goliad",
"Adventure Time Season 4 Episode 9 – Hug Wolf",
"Adventure Time Season 4 Episode 8 – Princess Monster Wife",
"Adventure Time Season 4 Episode 7 – In Your Footsteps",
"Adventure Time Season 4 Episode 6 – Daddy’s Little Monster",
"Adventure Time Season 4 Episode 5 – Return to the Nightosphere",
"Adventure Time Season 4 Episode 4 – Dream of Love",
"Adventure Time Season 4 Episode 3 – Web Weirdos",
"Adventure Time Season 4 Episode 2 – Five Short Graybles",
"Adventure Time Season 4 Episode 1 – Hot to the Touch",
"Adventure Time Season 3 Episode 26 – Incendium",
"Adventure Time Season 3 Episode 25 – Dad’s Dungeon",
"Adventure Time Season 3 Episode 24 – Another Way",
"Adventure Time Season 3 Episode 23 – Paper Pete",
"Adventure Time Season 3 Episode 22 – The Monster",
"Adventure Time Season 3 Episode 21 – Marceline’s Closet",
"Adventure Time Season 3 Episode 20 – Holly Jolly Secrets Part II",
"Adventure Time Season 3 Episode 19 – Holly Jolly Secrets Part I",
"Adventure Time Season 3 Episode 18 – The New Frontier",
"Adventure Time Season 3 Episode 17 – Thank You",
"Adventure Time Season 3 Episode 16 – Jake vs. Me-Mow",
"Adventure Time Season 3 Episode 15 – No One Can Hear You",
"Adventure Time Season 3 Episode 14 – Beautopia",
"Adventure Time Season 3 Episode 13 – From Bad to Worse",
"Adventure Time Season 3 Episode 12 – The Creeps",
"Adventure Time Season 3 Episode 11 – Apple Thief",
"Adventure Time Season 3 Episode 10 – What Was Missing",
"Adventure Time Season 3 Episode 9 – Fionna and Cake",
"Adventure Time Season 3 Episode 8 – Wizard Battle",
"Adventure Time Season 3 Episode 7 – Still",
"Adventure Time Season 3 Episode 6 – The Monster",
"Adventure Time Season 3 Episode 5 – Too Young",
"Adventure Time Season 3 Episode 4 – Hitman",
"Adventure Time Season 3 Episode 3 – Memory of a Memory",
"Adventure Time Season 3 Episode 2 – Morituri te Salutamus",
"Adventure Time Season 3 Episode 1 – Conquest of Cuteness",
"Adventure Time Season 2 Episode 26 – Heat Signature",
"Adventure Time Season 2 Episode 25 – Mortal Folly",
"Adventure Time Season 2 Episode 24 – Mortal Recoil",
"Adventure Time Season 2 Episode 23 – Video Makers",
"Adventure Time Season 2 Episode 22 – The Limit",
"Adventure Time Season 2 Episode 21 – Belly of the Beast",
"Adventure Time Season 2 Episode 20 – Go With Me",
"Adventure Time Season 2 Episode 19 – Mystery Train",
"Adventure Time Season 2 Episode 18 – Susan Strong",
"Adventure Time Season 2 Episode 17 – Death in Bloom",
"Adventure Time Season 2 Episode 16 – Guardians of Sunshine",
"Adventure Time Season 2 Episode 15 – The Real You",
"Adventure Time Season 2 Episode 14 – The Silent King",
"Adventure Time Season 2 Episode 13 – The Pods",
"Adventure Time Season 2 Episode 12 – Her Parents",
"Adventure Time Season 2 Episode 11 – Crystals Have Power",
"Adventure Time Season 2 Episode 10 – To Cut a Woman’s Hair",
"Adventure Time Season 2 Episode 9 – The Other Tarts",
"Adventure Time Season 2 Episode 8 – The Chamber of Frozen Blades",
"Adventure Time Season 2 Episode 7 – Power Animal",
"Adventure Time Season 2 Episode 6 – Slow Love",
"Adventure Time Season 2 Episode 5 – Storytelling",
"Adventure Time Season 2 Episode 4 – Blood Under the Skin",
"Adventure Time Season 2 Episode 3 – Loyalty to the King",
"Adventure Time Season 2 Episode 2 – The Eyes",
"Adventure Time Season 2 Episode 1 – It Came From the Nightosphere",
"Adventure Time Season 1 Episode 26 – Gut Grinder",
"Adventure Time Season 1 Episode 25 – His Hero",
"Adventure Time Season 1 Episode 24 – What Have You Done?",
"Adventure Time Season 1 Episode 23 – Rainy Day Daydream",
"Adventure Time Season 1 Episode 22 – Henchman",
"Adventure Time Season 1 Episode 21 – Donny",
"Adventure Time Season 1 Episode 20 – Freak City",
"Adventure Time Season 1 Episode 19 – The Duke",
"Adventure Time Season 1 Episode 18 – Dungeon",
"Adventure Time Season 1 Episode 17 – When Wedding Bells Thaw",
"Adventure Time Season 1 Episode 16 – Ocean of Fear",
"Adventure Time Season 1 Episode 15 – What Is Life?",
"Adventure Time Season 1 Episode 14 – The Witch’s Garden",
"Adventure Time Season 1 Episode 13 – City of Thieves",
"Adventure Time Season 1 Episode 12 – Evicted!",
"Adventure Time Season 1 Episode 11 – Wizard",
"Adventure Time Season 1 Episode 10 – Memories of Boom Boom Mountain",
"Adventure Time Season 1 Episode 9 – My Two Favorite People",
"Adventure Time Season 1 Episode 8 – Business Time",
"Adventure Time Season 1 Episode 7 – Ricardio the Heart Guy",
"Adventure Time Season 1 Episode 6 – The Jiggler",
"Adventure Time Season 1 Episode 5 – The Enchiridion!",
"Adventure Time Season 1 Episode 4 – Tree Trunks",
"Adventure Time Season 1 Episode 3 – Prisoners of Love",
"Adventure Time Season 1 Episode 2 – Trouble in Lumpy Space",
"Adventure Time Season 1 Episode 1 – Slumber Party Panic",
];

document.getElementById('random-button').addEventListener('click', () => {
    const randomIndex = Math.floor(Math.random() * episodes.length);
    const randomEpisode = episodes[randomIndex];
    document.getElementById('episode-display').innerText = randomEpisode;
});
